Added function to get id from name
black-sliver/apclientpp pull request #5
Opened 2022-05-13 20:19 UTC by nature1996

Added a way to access the ID using the location or item name. Added a documentation saying using those methods isn't recomended

2022-05-14 10:05 UTC, black-sliver requested changes

2022-05-14 10:05 UTC, black-sliver commented on apclient.hpp
> +        return -1;
Item -1 is Archipelago's "Nothing". If this is what you want to return that's fine, but maybe add a comment to clarify -1 is a valid item.

2022-05-14 10:05 UTC, black-sliver commented on apclient.hpp
> +        return -1;
Location -1 is Archipelago's "Cheat Console". Not sure that's ideal.
* -2 would be Archipelago's "Server"
* `std::numeric_limits<int64_t>::min()` would definitely be invalid, if that's the goal
  * requires `#include<limits>` on top of the file
  * could be added as a constant with `static constexpr INVALID_LOCATION = std::numeric_limits<int64_t>::min();` to make code more readable

2022-05-21 16:19 UTC, nature1996 commented on apclient.hpp
> +        return -1;
Actually, we could trow an error, so they have to use a try/catch

2022-05-21 16:20 UTC, nature1996 commented on apclient.hpp
> +        return -1;
Could also do the same with error code

2022-05-21 16:59 UTC, nature1996 commented on apclient.hpp
> +        return -1;
Should be solved with commit [bae7be9](https://github.com/black-sliver/apclientpp/pull/5/commits/bae7be9d1c64d095812c1b4c70a2bc14b34df4f7)

2022-05-21 16:59 UTC, nature1996 commented on apclient.hpp
> +        return -1;
Should be solved with commit [bae7be9](https://github.com/black-sliver/apclientpp/pull/5/commits/bae7be9d1c64d095812c1b4c70a2bc14b34df4f7)

2022-05-27 19:21 UTC, black-sliver commented
So we don't forget: this could simplified using `...["location_name_to_id].value<int64_t>(name, INVALID_NAME_ID)` instead of writing that loop yourself (`.value` will do the loop under the hood); will merge as is to get that feature in. Just make a new PR when you want to clean it up.

2022-05-27 19:21 UTC, merged